### Entry point of api
GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjEyLCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQxNTk2OTE5LCJleHAiOjE3NDE2ODMzMTl9.nXnwADMN0iWs1zrnuSfXKxt_A5y2EeV5tIZ8F8V6FtY

### Fetch all songs
GET http://localhost:3000/songs

### Fetch one song by id
GET http://localhost:3000/songs/2

### Create new song
POST http://localhost:3000/songs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjEyLCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQxNTk2OTE5LCJleHAiOjE3NDE2ODMzMTl9.nXnwADMN0iWs1zrnuSfXKxt_A5y2EeV5tIZ8F8V6FtY

{
    "title": "You for me",
    "artists": [1, 2],
    "releaseDate": "2022-09-11",
    "duration": "02:23",
    "lyrics": "asdfasdfasdfasdfasdf"
}

### Update one song by id
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
    "title": "Mr. Lonely3",
    "artists": ["MC yakışıklı", "Mert Şakar2"],
    "releaseDate": "2022-09-11",
    "duration": "02:23",
    "lyrics": "asdfasdfasdfasdfasdf"
}

### Delete one song by id
DELETE  http://localhost:3000/songs/1

### Create new playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "playlist1",
    "songs": [2, 6,7],
    "user": 1
}

### User Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Mert",
    "lastName": "Sakar",
    "email": "mertsakar2@hotmail.com",
    "password": "123456"
}

### Artist Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Martin",
    "lastName": "Garrix",
    "email": "martingarrix@gmail.com",
    "password": "123456"
}

### User Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "martingarrix@gmail.com",
    "password": "123456"
}

### Artist Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "martingarrix@gmail.com",
    "password": "123456"
}

### Enable 2FA
GET http://localhost:3000/auth/enable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjEyLCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQ0NzIwMzk3LCJleHAiOjE3NDQ4MDY3OTd9.3US72V2lhSbUTNj0US2oddGdd_y8wbHtubV-GdO0AGk

### Validate 2FA
POST http://localhost:3000/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjEyLCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQ0NzE3MTU1LCJleHAiOjE3NDQ4MDM1NTV9.-UlD0y_AA3UrwuIEoMwf1pxVJL7P-5eA_qVwvCGvR2c
Content-Type: application/json

{
    "token": "212719"
}

### Disable 2FA
GET http://localhost:3000/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdhcnJpeEBnbWFpbC5jb20iLCJ1c2VySWQiOjEyLCJhcnRpc3RJZCI6MSwiaWF0IjoxNzQ0NzE3MTU1LCJleHAiOjE3NDQ4MDM1NTV9.-UlD0y_AA3UrwuIEoMwf1pxVJL7P-5eA_qVwvCGvR2c


### Access profile
GET http://localhost:3000/auth/profile
Authorization: Bearer a0434fcb-308f-4267-82fe-f33283c119bc