### Entry point of api
GET http://localhost:3000/

### Fetch all songs
GET http://localhost:3000/songs

### Fetch one song by id
GET http://localhost:3000/songs/2

### Create new song
POST http://localhost:3000/songs/
Content-Type: application/json

{
    "title": "You for me",
    "artists": [1, 2],
    "releaseDate": "2022-09-11",
    "duration": "02:23",
    "lyrics": "asdfasdfasdfasdfasdf"
}

### Update one song by id
PUT http://localhost:3000/songs/2
Content-Type: application/json

{
    "title": "Mr. Lonely3",
    "artists": ["MC yakışıklı", "Mert Şakar2"],
    "releaseDate": "2022-09-11",
    "duration": "02:23",
    "lyrics": "asdfasdfasdfasdfasdf"
}

### Deşete one song by id
DELETE  http://localhost:3000/songs/1

### Create new playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
    "name": "playlist1",
    "songs": [2, 6,7],
    "user": 1
}

### Create new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Mert",
    "lastName": "Şakar",
    "email": "mertsakar12@hotmail.com",
    "password": "asdf123"
}